### ISSUE TITLE
How current is this?

### ISSUE THREAD

**Issue by Rod-in-NM** [Kekos/gs1-csharp#1]
I'm going to be working on a GS1 interface. I've only recently learned of the term, so have been reading about it. I thought I'd check out various GS1 packages available in NuGet, which directed me here. I've been referred to a [GS1 Messaging document](https://www.gs1.org/docs/standards/gs1_lightweight_verification_messaging_standard_v_1_0_2.pdf) which indicates that they're talking about version 1.0.2. Does this gs1-csharp package accommodate version 1.0.2?

**Comment by Kekos** [comment]
Thank you for your question and interest in this project.

This project only implements the GTIN standard, which is only a subset of the GS1 standard for identifications. The document you're referring to only standardizes the communications protocol for verifying SGTIN (GTIN and a serial number) against a database. That communications protocol will never be a subject for this project.

To answer your question, this project is current but the purpose is only for encoding and decoding the different identifiers within the GS1 standard.
